In [1]:
import grid2op
import os
import sys
import numpy as np
import grid2op
from tqdm import tqdm


from grid2op.dtypes import dt_int
from grid2op.Runner import Runner
from grid2op.Chronics import ChangeNothing
from grid2op.Agent import BaseAgent
from grid2op.Reward import BaseReward, RedispReward, L2RPNSandBoxScore, _AlarmScore
from grid2op.Action import TopologyAndDispatchAction

agent_name="02_56_richard_wth"#"01_63_maze-rl"
submission_dir=os.path.join('/pathTo/submissions/',agent_name)
path_save_dir='./res_test_wcci_2022'
os.makedirs(path_save_dir,exist_ok=True)

submission_location = os.path.join(submission_dir, "submission")
print(submission_location)

# add proper directories to path
#sys.path.append(program_dir)
sys.path.append(submission_dir)




/home/marotant/.local/lib/python3.8/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.9.1-CAPI-1.14.2). Conversions between both will be slow.
  warnings.warn(


/home/marotant/Téléchargements/2022_L2RPN_results_cpy/submissions/02_56_richard_wth/submission


## Loading grid2op environment

In [7]:
#grid2op.make("/home/marotant/Téléchargements/L2RPN_wcci2022_starting_kit/input_data_local/")
env=grid2op.make("L2RPN_wcci_2022")


In [9]:
from submission import make_agent
#env_template = grid2op.make(env_path),
#                            chronics_class=ChangeNothing,
#                            action_class=TopologyAndDispatchAction)
#env = grid2op.make(env_path,backend=BACKEND(),reward_class=L2RPNSandBoxScore,other_rewards={'attention_score':_AlarmScore}
                   

submitted_agent = make_agent(env, submission_location)
#from l2rpn_baselines.ExpertAgent import ExpertAgent
#from grid2op.Agent.greedyAgent import GreedyAgent
#from grid2op.Agent.doNothing import DoNothingAgent
#from grid2op.Agent.randomAgent import RandomAgent
#submitted_agent=DoNothing_Attention_Agent(env.action_space,env.alarms_lines_area)#,env.observation_space)

#submitted_agent=ExpertAgent(env.action_space,env.observation_space,name="expert_run",gridName="IEEE118_R2")#RandomAgent(env.action_space)#

In [44]:
action_space_zz=submitted_agent.action_space_zz
for i in range(70):#len(action_space_zz)):
    print("index:"+str(i))
    action=action_space_zz[i]
    sub_id=action.impact_on_objects()['topology']['bus_switch'][0]['substation']
    print(sub_id)
    obs=env.reset()
    obs_simulated,_,_,_=obs.simulate(action)
    print(obs_simulated.sub_topology(sub_id))

index:0
68
[1 2 1 1 2 1 2]
index:1
58
[1 1 1 2 1 1 2 2 1 1]
index:2
58
[1 1 1 2 1 2 1 1 1 1]
index:3
55
[1 2 2 2 1 1 1 1 2 2]
index:4
99
[1 1 2 2 1 2 2 2 1 1 2 2]
index:5
68
[1 2 1 1 2 1 1]
index:6
99
[1 1 1 2 1 2 2 2 2 1 2 2]
index:7
99
[1 1 2 1 1 2 2 2 1 1 1 2]
index:8
67
[1 1 2 1]
index:9
99
[1 1 2 2 1 2 2 2 1 2 1 2]
index:10
99
[1 1 1 2 1 2 2 2 1 1 2 2]
index:11
48
[1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 2]
index:12
68
[1 2 2 2 1 1 2]
index:13
22
[1 1 1 2 1 1]
index:14
55
[1 1 1 1 2 2 2 1 1 2]
index:15
68
[1 1 1 1 2 2 1]
index:16
68
[1 1 1 1 2 2 2]
index:17
67
[1 2 1 2]
index:18
16
[1 2 1 2 2 2 2]
index:19
68
[1 2 2 2 2 1 1]
index:20
99
[1 1 2 1 1 2 2 2 1 2 1 2]
index:21
76
[1 2 1 2 1 1 1 1 1 2 1]
index:22
68
[1 1 1 1 1 2 2]
index:23
68
[1 2 2 2 1 1 1]
index:24
58
[ 1  1  1 -1  1  2  2  2  1  1]
index:25
11
[1 1 2 1 1 1 2 1 1]
index:26
54
[1 1 2 2 2]
index:27
58
[1 1 1 2 2 1 1 1 1 1]
index:28
58
[1 1 1 2 1 1 2 2 2 1]
index:29
16
[1 2 1 2 1 2 2]
index:30
68
[1 1 2 2 1 2 2]
index:31
68
[1 1

In [42]:
i=54
action=action_space_zz[i]
sub_id=action.impact_on_objects()['topology']['bus_switch'][0]['substation']
print(sub_id)
obs=env.reset()
obs_simulated,_,_,_=obs.simulate(action)
print(obs_simulated.sub_topology(sub_id))

60
[1 1 1 2 2]


In [43]:
from grid2op.PlotGrid import PlotPlotly #PlotMatplot
plot_helper = PlotPlotly(env.observation_space)
obs_simu, reward, done, _=obs.simulate(action=action)
fig = plot_helper.plot_obs(obs_simu,line_info=None,
                                  load_info=None,  # i don't plot anything concerning the load
                                  gen_info=None)
fig.show()

print(action)